name: Testing and deployment

on:
  push:
    branches:
      - developer

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: root # default root password to use must be 'root'
      DB_HOST: "127.0.0.1"
      DB_PORT: "3306"
      DB_DATABASE: share_a_meal
      DB_USER: root
      DB_PASSWORD: root
    services:
      mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
    steps:
      - uses: actions/checkout@main

      - name: Start MySQL service
        run: docker run --name mysql -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${{ env.MYSQL_ROOT_PASSWORD }} mysql:5.7

      - name: Wait for MySQL service to start
        run: sleep 10

      - name: Import database script
        run: |
          mysql -h${{ env.DB_HOST }} -P${{ env.DB_PORT }} -uroot -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < share-a-meal.sql
          mysql -h${{ env.DB_HOST }} -P${{ env.DB_PORT }} -uroot -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} -e "SHOW TABLES;"

      - name: npm install
        run: |
          npm install

      - name: npm test
        run: |
          npm run test -- --DB_PASSWORD ${{ env.MYSQL_ROOT_PASSWORD }} --DB_USER root --DB_NAME ${{ env.DB_DATABASE }}
